### 회원가입 유저 생성
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "qwa406@naver.com",
  "password": "password",
  "nickname": "시월",
  "username": "qwa406@naver.com",
  "role" : "admin",
  "roleNumber" : 1,
  "ip": "1.1.1.1"
}

### 회원가입 유저 생성2
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "zxa406@naver.com",
  "password": "password",
  "nickname": "은별",
  "username": "zxa406@naver.com",
  "role" : "user",
  "roleNumber" : 2,
  "ip": "2.2.2.2"
}


### 로그인
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "qwa406@naver.com",
  "password": "password"
}

### 인증 - AuthGuard
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InF3YTQwNkBuYXZlci5jb20iLCJ1c2VySWQiOjEsImlhdCI6MTcxNTk5Njk3NiwiZXhwIjoxNzE1OTk3NTc2fQ.m2lg6Tgwqu5j2KQMVATzZjJc5VeABAZ_whjy_GiYfIo

### refreshToken이용 발급
POST http://localhost:3000/auth/refreshToken

### 모든 유저 정보 get
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inp4YTQwNkBuYXZlci5jb20iLCJ1c2VySWQiOjIsImlhdCI6MTcxNjQ5MDMwMSwiZXhwIjoxNzE2NDkwOTAxfQ.h-HDphscAz1SGG1mcfTUotGibj6XJkj_SA4Ra9SzFM0


### report 생산
POST http://localhost:3000/reports
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InF3YTQwNkBuYXZlci5jb20iLCJ1c2VySWQiOjEsImlhdCI6MTcxNTk5ODI3OCwiZXhwIjoxNzE1OTk4ODc4fQ.gRAtrJVfUHvvSjjL5lDafHBUeWPDySuqsvAX0S4JXjs

{
  "title":"나는 신이다",
  "content":"아 진자 졸라 힘들어 쉬고싶다. 자고싶다.....",
  "level": 1
}

### report보기
GET  http://localhost:3000/reports
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InF3YTQwNkBuYXZlci5jb20iLCJ1c2VySWQiOjEsImlhdCI6MTcxNjQ5OTkzMCwiZXhwIjoxNzE2NTAwNTMwfQ.0RT5Iy1HHc7NtlXvH33pefWDSYwLLVU71-SiT0D-5Lg

### 회원가입 인증 토큰 보내기
POST http://localhost:3000/users/email-verify-token
Content-Type: application/json

{
  "email":"siwol406@gmail.com"
}