### 회원가입 유저 생성
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "dongwoo3",
  "lastName": "kim3",
  "username": "kimdongwoo3",
  "password": "test",
  "isActive": true
}


### 인증 - AuthGuard
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoia2ltZG9uZ3dvbyIsImlhdCI6MTcxNDQxMzk2MiwiZXhwIjoxNzE0NDE0MDIyfQ.PWOZnAiYeFTwtgcWiOMDCixa_LnYXvRCCqkVfFY6PgA
