### 회원가입 유저 생성
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "admin2",
  "password": "admin2"
}

### 로그인
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "admin2",
  "password": "admin2"
}

### 인증 - AuthGuard
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoxLCJpYXQiOjE3MTQ1Mjg3MDYsImV4cCI6MTcxNDUyODc2Nn0.Yqj_kqri_Ag6IBl_suhcuJHCJwnRaorF6Cofd9J6XCQ

